### PR TITLE
update dep, move to ESM and require 12.20

### PR DESCRIPTION
**Pull request by jimmywarting**
would also think this breaking change would be a grate opportunity to convert to using promises also.

### CODE REVIEW

**Comment by lydell** [comment]
Something like this should be done on the [next](https://github.com/lydell/source-map-resolve/tree/next) branch which already uses promises (and which I feel pretty bad about never having released).

I’m going to copy in a message I wrote once in a Discord channel, asking me about the source-map-resolve package:

> While that package does have a lot of downloads, many of the downloads are due to really bad dependency chains of semi-deprecated stuff :dizzy_face: 
>
> It does do the job and is fairly well tested, but as I said here: https://github.com/lydell/source-map-resolve/issues/9#issuecomment-699002149
>
> > I really dislike this package, so don’t expect anything. Try to use a different dependency if you can.
>
> I made this a _long_ time ago, so it has some pretty weird stuff in it.
>
> There’s a branch that uses promises here https://github.com/lydell/source-map-resolve/pull/20 that I never released and feel really bad about – the person who made that PR put down a lot of effort that has never been released :cry: 
>
> I’ve tried to come back to this package many times, but I always end up doing nothing in frustration. Source maps are so underspecified so it’s super hard to know how things should work and what the module should really do, and requires a lot of research on how different browsers behave…
>
> All in all, I’m always a bit sad when I’m reminded about that package. It might help you, but it might also serve better as inspiration for doing stuff yourself in a better way

**What’s your motivation for doing this?**

**Comment by jimmywarting** [comment]
> What’s your motivation for doing this?

It's all really about getting at least one (or few) sub package (including dev dependencies) to switch to become a ESM only package, then the rest of the top dependencies must also use ESM if they want updates. 
My end goal is to get the package I want to become a ESM package too, but they are not willing to do that yet 
So I'm tackling this from behind 😛

All in all it is just to get it to become better Deno compatible

**Comment by lydell** [comment]
>  My end goal is to get the package I want to become a ESM package too, but they are not willing to do that yet

Out of curiosity, which package is that?

**Comment by jimmywarting** [comment]
> Out of curiosity, which package is that?

https://www.npmjs.com/package/node-wifi

**Comment by lydell** [comment]
Looking at the graph you linked to, node-wifi doesn’t even depend on source-map-resolve?

**Comment by jimmywarting** [comment]
check the dev dependencies switch

**Comment by lydell** [comment]
712 modules. Ambitious!

I think “all” you need to do to get rid of source-map-resolve is to upgrade from Jest 26 to Jest 27 in node-wifi. That would be time better spent. And you’ll get rid of more deprecated packages, like `sane`.

**Comment by jimmywarting** [comment]
sooo, what will it be? merging or deprecating this?

**Comment by lydell** [comment]
I deprecated it.

**Pull request closed without merging**
