### PR TITLE
Rewrite async API to use promises

### PR DESCRIPTION
**Pull request by andy128k**
Related to item 2 in https://github.com/lydell/source-map-resolve/issues/12

### CODE REVIEW

**Comment by lydell** [comment]
Hi! Wow, I did not expect anyone to come and do this! Amazing!

I’m curious – what’s your motivation to dive into this shitty code base? Just for “fun”? Do you use source-map-resolve and miss the async API? How far would you like to take the refactor?

**Comment by andy128k** [comment]
Hi

I was bored. And then `yarn` showed me this:

```
warning babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

... 

I do not use source-map-resolve directly.

If you still have such tasks I can try to do them too.

**Comment by lydell** [comment]
If your goal is to get rid of those deprecation warnings, then you need to know:

- source-map-resolve 0.6.0 already got rid of the deprecated dependencies.
- You’d spend your time better trying to fix that dependency chain. For example, the latest version of `micromatch` does not even depend on snapdragon anymore.

**Comment by andy128k** [comment]
My goal was to entertain myself. I don't care about those warnings that much.

**Comment by lydell** [comment]
Ok!

Here are some ideas I’ve played around with:

- The test suite covers a lot of cases, but is horrible to work with. I’d like to structure the tests in a better way, and use Jest.
- Maybe we can get rid of the sync functions since we’ve got `await` these days.
- Nicer API, that works well with TypeScript. Maybe write the whole thing in TypeScript?
- ESLint instead of JSHint.
- Prettier.
- etc.

**Comment by andy128k** [comment]
Preview of conversion to Jest: https://github.com/lydell/source-map-resolve/commit/515124fa3724c5ff070bb4befc32be2c9a9fa84f

Like this?

**Comment by andy128k** [comment]
If you plan to get rid of sync functions it is better to do this before conversion to Jest. :)

**Comment by lydell** [comment]
Yeah, something like that.

Let’s get rid of the sync functions then!

Also, if you want to go the TypeScript route that’s probably good to do before tests, too.

**Comment by lydell** [comment]
I think it would be easier to merge all your PRs into one giant update-all-the-things PR. What do you think?

**Comment by andy128k** [comment]
https://github.com/lydell/source-map-resolve/pull/20 All changes are there

**Comment by lydell** [comment]
Closing in favor of #20.

**Pull request closed without merging**
