### PR TITLE
Switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by lydell** [comment]
Nice!

Can you:

- Switch to this config: https://github.com/prettier/eslint-config-prettier/blob/master/.github/workflows/ci.yml

  Then we get caching and testing on Windows.

- Remove all traces of Travis CI.

**Comment by lydell** [comment]
Can you copy the caching stuff from https://github.com/prettier/eslint-config-prettier/blob/master/.github/workflows/ci.yml as well? Really, you should be able to copy that file as-is to this repo, I think.

**Comment by lydell** [comment]
The tests seem to fail :(

https://github.com/andy128k/source-map-resolve/runs/561705274?check_suite_focus=true

**Comment by andy128k** [comment]
@lydell  Looks like it never worked. Travis runs tests on Node v13 while here we have 10 and 12 (stable ones).

BTW, Jest fails similarly, but config option `"testEnvironment": "node"` fixes it.

**Comment by lydell** [comment]
Do you think you can fix it?

**Comment by andy128k** [comment]
What do you want me to fix? Tape test  on node 10.x? Why?

**Comment by lydell** [comment]
I want to merge this. But not if it’s failing. Can you do whatever it takes to make it pass for now? Like disabling something for now, I don’t know. I read this super quickly and don’t understand the problem fully yet.

**Comment by andy128k** [comment]
The issue is that on Node >= 12 [this](https://github.com/lydell/source-map-resolve/blob/master/index.js#L136) is `false`, while on Node 10.x it is `true`. And string is decoded differently.

I can remove Node 10.x from this action.

**Comment by lydell** [comment]
Awesome, thanks!

**Pull request merged**
